### ISSUE TITLE
[1.18.2] Game hang when using 1x1 textures and opening AV

### ISSUE THREAD

**Issue by Chaos02** [XFactHD/AtlasViewer#3] opened 2023-08-18 22:36 UTC
title says it all, game log is sadly completely spammed and cannot be uploaded anywhere because of its size
Let me know if you have any questions tho, I'm pretty active here!

AtlasViewer-1.1.0.jar

**Comment by XFactHD** [comment] 2023-08-19 15:17
GitHub's own paste site, https://gist.github.com, has a 100 MB upload limit. If that's still not enough and the messages are just repeating, then cut off the duplicate messages so it fits within that limit. I would also appreciate a link to an applicable resource pack so I can test the fix.

**Comment by XFactHD** [comment] 2023-08-24 15:02
I currently cannot reproduce this issue on any version (tested 1.18.2, 1.19.2 and 1.20.1) with a minimal test case (replacing a single block texture with a 1x1 texture) and can't find any 1x1 resource packs from trustworthy sources, so I would really appreciate your input to be able to debug this further.

**Comment by Chaos02** [comment] 2023-08-27 16:00
ohhh I've been creating a patch to lower the size of my texture atlas in a big modpack (because there are many wasteful textures) and I've been copying and then just downscaling a bunch of textures - there were a couple basically empty textures (like the ae2 quartz glass) that I just scaled to 1x1 and it caused the problem.

regarding the logs - sadly they have already been deleted as I've been playing in the mean time.
Here is the "pack" I've used when I encountered the issue - actually it's just a small excerpt from it but it should be enough to replicate:
[test.zip](https://github.com/XFactHD/AtlasViewer/files/12448354/test.zip)

To downscale the images I've used Windows Powertoys' `Resize images` which all worked well for higher resolutions.

**Comment by XFactHD** [comment] 2023-08-27 21:07
When testing with the pack you provided in an environment with Forge 1.18.2-40.1.60, AtlasViewer 1.1.0 and AppliedEnergistics 2 11.7.5, I still cannot reproduce the error. My guess is that this is a hardware- and/or driver-dependent issue. Please provide which GPU and GPU driver version you are using. I would also appreciate it if you could try reproducing the error again and provide logs if you are able to reproduce it again.

**Comment by Chaos02** [comment] 2023-08-28 16:08
huh damn didn't think that was possible...
To clarify: the hang only occurs when opening the AtlasViewer.

I have a Radeon RX 6800 and a week ago I was on driver 23.7.X iirc

If I find the time to reproduce I will

**Comment by XFactHD** [comment] 2024-01-11 22:27
I completely forgot to close this issue. I did find out that the most likely cause of this issue is that the depth of the quadtree used for determining which sprite your cursor is pointing at can grow too far with very large atlases and/or very small sprites and due to the way this data structure works, this can quickly consume large amounts of RAM, even on machines with lots of RAM. [This](https://github.com/XFactHD/AtlasViewer/commit/cf9154bbe6383a19a3a74c9a0cb62f6dbc45e29e) commit, which was released in 5.1.0 for 1.20.1, fixes this issue and should fix the issue you ran into. Sadly I currently don't have the time to backport this fix to older versions as mentioned on other issues.

**Closed as completed by XFactHD** 2024-01-11 22:27 UTC
